/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElCascaderMenu: typeof import('element-plus/es')['ElCascaderMenu']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElTYPE: typeof import('element-plus/es')['ElTYPE']
}
